export const initialMails = [
  {
    id: "1",
    sender: "Sarah Connor",
    email: "sarah@cyberdyne.com",
    subject: "Project Nebula Roadmap Review",
    snippet: "Hey team, here is the updated roadmap for the upcoming release...",
    body: "Hey team,\n\nHere is the updated roadmap for the upcoming release. Please review the milestones and share your feedback before our sync on Friday.\n\nBest,\nSarah",
    timestamp: "10:42 AM",
    folder: "inbox",
    isRead: false,
    isStarred: true,
  },
  {
    id: "2",
    sender: "Alex Rivera",
    email: "alex.r@designstudio.io",
    subject: "New UI Components for Nebula Mail",
    snippet: "I've finalized the Figma designs for the sidebar and email detail panel...",
    body: "Hi there,\n\nI've finalized the Figma designs for the sidebar and email detail panel. You can check the latest component library link in the design system channel.\n\nCheers,\nAlex",
    timestamp: "Yesterday",
    folder: "inbox",
    isRead: true,
    isStarred: false,
  },
  {
    id: "3",
    sender: "Hiring Team",
    email: "careers@nebula.io",
    subject: "Nebula Web App Hiring Task Details",
    snippet: "Welcome to the hiring task! Please implement the email client UI...",
    body: "Hello candidate,\n\nWelcome to the hiring task! Please implement the email client UI with responsive design, state management, and clear code organization.\n\nGood luck!",
    timestamp: "Sep 5",
    folder: "inbox",
    isRead: true,
    isStarred: false,
  },
  {
    id: "4",
    sender: "Me",
    email: "user@nebula.io",
    subject: "Submitted Assessment Code",
    snippet: "Hi Team, I have completed the task and pushed the repository...",
    body: "Hi Team,\n\nI have completed the task and pushed the repository to GitHub. Looking forward to your feedback.\n\nRegards,",
    timestamp: "Sep 4",
    folder: "sent",
    isRead: true,
    isStarred: false,
  }
];